name = "RER"
author = "ModogTheDev, KarlBH"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "301be209dac134459f2c87692bd2caa2086a62e80b65d93b60074a2bfc5db3be"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
