name = "RER"
author = "ModogTheDev, KarlBH"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad412b41b226c6b9ce0b9369e481f96e475ffa7b683efb935da1ce7f2d20761a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.225"
