name = "RER"
author = "ModogTheDev, KarlBH"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b74444d335ca11f44a8ad45d09a7cddbbeb908833023020d90f8029d30a4a88"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.225"
